---
title: "Syd Competitive Programming 2019 03 09"
output:
  html_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

## The leaderboard
```{r add_data, include=FALSE}
library(data.table)
library(magrittr)
library(dplyr)
df = data.table()

num_attendees = 15

add_solution <- function(df, name, prob, bytes, valid) {
  rbindlist(
    list(
      df, 
      data.table(name = name, prob = prob, bytes = bytes, valid=valid)), 
      fill = F, use.names = T)
};

df %<>% 
  add_solution("Michael Jones", 2, 437,T) %>% 
  add_solution("Yiqun", 2, 261, T) %>% 
  add_solution("Jennivine", 2, 199, T) %>% 
  add_solution("jin", 2, 637, T) %>% 
  add_solution("Kale Miller", 2, 116, T) %>% 
  add_solution("Kale Miller", 2, 46, T) %>% 
  add_solution("feng", 2, 176, T) %>% 
  add_solution("Osber", 2, 353, F) %>% 
  add_solution("Andrew Martin", 2, 276, T) %>% 
  add_solution("Jennivine", 1, 1513, T) %>% 
  add_solution("Osber", 2, 399, T) %>% 
  add_solution("Michael Jones", 1, 3884, T) %>% 
  add_solution("dtpearl", 2, 131, T) %>% 
  add_solution("Jennivine", 3, 206, T) %>% 
  add_solution("Yuchen", 2, 329, T) %>% 
  add_solution("Kale Miller", 3, 1079, T) %>% 
  add_solution("feng", 3, 1095, T) %>% 
  add_solution("ZJ",2,60,T) %>% 
  add_solution("ZJ",2,53,T) %>% 
  add_solution("Michael Jones",3,8805,T) %>% 
  add_solution("feng", 2, 636, T) %>% 
  add_solution("Yiqun", 3, 1073, T) %>% 
  add_solution("ZJ",3,193,T)

df[,seq := 1:.N]

df[, pts := 0L]
df[, penalty := n_distinct(name), .(prob)]

data.table::fwrite(df, "data_processed.csv")
```

```{r logic2, echo=FALSE, message=FALSE, warning=FALSE}
#
score_submission <- function(probn) {
  df2 = copy(df[prob == probn & valid == T,])

  # remove duplicates
  df2[,min_seq := min(seq), name]
  
  df3 = df2[min_seq == seq,]
  
  df3[order(seq), placing_penaly := 1:.N]
  df3[, pts := 2*num_attendees - penalty + 1 - placing_penaly]
  df3
}

df_summ = purrr::map_dfr(1:3, ~{
  score_submission(.x)
})

df_summ2 = df_summ[,.(pts = sum(pts)), name]

data.table::fwrite(df_summ2, "data_processed_summ.csv")
```


```{r code_golf, include=FALSE}
golf_score = function(probn) {
  df_g = df[(valid == T) & (prob == probn), ]
  df_g[order(bytes), seq_golf := 1:.N]
  
  df_g2 = df_g
  if(nrow(df_g) > 0) {
    df_g[, min_seq_golf := min(seq_golf), name]
    df_g2 = df_g[min_seq_golf == seq_golf, ]
  }
  
  
  df_g2[order(seq_golf), golf_placing_penaly := 1:.N]
  df_g2[, pts_golf := 2*num_attendees - penalty + 1 - golf_placing_penaly]
  df_g2[order(seq_golf),]
}

golf_scrs = purrr::map_dfr(1:3, ~golf_score(.x))
golf_scrs[,.(name, pts_golf)]
```

```{r tot, echo=FALSE, message=FALSE, warning=FALSE}
golf_scrs2 = golf_scrs[,.(name, pts = pts_golf)]

df_summ3 = rbindlist(list(df_summ2, golf_scrs2), fill = T, use.names = T)

df_summ4 = df_summ3[,.(pts = sum(pts)), name]

DT::datatable(df_summ4[order(pts, decreasing = T), ])
```


# Points by rank

```{r plot, echo=FALSE, dependson=df_summ2, cache=FALSE}
library(data.table)
df_summ5 = df_summ4[order(pts, decreasing = T), ]
barplot(df_summ5$pts, names.arg = df_summ5$name, cex.names = 0.6)
```

# Points from first to submit
```{r echo=FALSE}
DT::datatable(df_summ2[,.(pts=sum(pts)), name][order(pts, decreasing = T)])
```

# Points from golf
```{r echo=FALSE}
DT::datatable(golf_scrs[,.(name, pts_golf = sum(pts_golf)), name][
  order(pts_golf, decreasing = T),
])
```
